# https://taskfile.dev

version: "3"

vars:
  PROJECT: masha
  DEMONDIR: /Library/LaunchDaemons

tasks:
  default:
    desc: run flask cli
    cmds:
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} python -m {{.PROJECT}} {{.CLI_ARGS}}

  env:
    desc: run in env
    cmds:
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} {{.CLI_ARGS}}

  run:
    desc: systemd exec
    dir: $WORKDIR
    cmds:
      - ./run.sh

  face2img:
    desc: face tasks
    cmds:
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} python -m {{.PROJECT}} image face2img {{.CLI_ARGS}}
  txt:
    desc: text to image
    cmds:
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} python -m {{.PROJECT}} image txt2img {{.CLI_ARGS}}

  img2img:
    desc: text to image
    cmds:
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} python -m {{.PROJECT}} image img2img {{.CLI_ARGS}}

  retrain:
    desc: retrain
    vars:
      TRAIN_CONFIG: "{{.CLI_ARGS}}c"
      INDEX_C: "{{.CLI_ARGS}}c"
      INDEX_E: "{{.CLI_ARGS}}e"
      INDEX_EL2: "{{.CLI_ARGS}}c"
    cmds:
      # - mamba run --live-stream -n {{.PROJECT}} flask face train {{.TRAIN_CONFIG}}
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} flask --app {{.PROJECT}} face index -c {{.INDEX_C}}
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} flask --app {{.PROJECT}} face index -c {{.INDEX_E}}
      - direnv exec . mamba run --live-stream -n {{.PROJECT}} flask --app {{.PROJECT}} face index -c {{.INDEX_EL2}}

  redis:
    desc: open redis-cli
    cmds:
      - keydb-cli $REDIS_CLI

  redis-face:
    cmds:
      - redis-cli $FACE_REDIS_CLI

  logs:
    desc: logs
    cmds:
      - tail -f ~/Library/Logs/net.cacko.masha/masha.log

  export:
    desc: export env
    cmds:
      - direnv exec . mamba env export --no-builds -n {{.PROJECT}} > environment.yml

  start:
    desc: start
    cmds:
      - sudo launchctl start net.cacko.masha

  stop:
    desc: stop
    cmds:
      - sudo launchctl stop net.cacko.masha

  restart:
    desc: stop
    cmds:
      - task: stop
      - sleep 10
      - task: start

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - gcom || true
      - git push || true

  restart-botyo:
    desc: restart restart-botyo
    dir: /Volumes/Devo/Code/botyo
    cmds:
      - task restart

  rehash:
    desc: rehash the image oiptions
    cmds:
      - task: restart
      - sleep 10
      - task: restart-botyo
