classify:
  model: vit-base-patch16-224
  tokenizer: vit-base-patch16-224
  attraction_model: attractive_faces_celebs_detection
  age_model: facial_age_image_detection
  ethnicity_model: Race-CLS-FairFace_yolo11x.pt
  gender_model: gender-classification-2
  dog_breed_model: Dog-Breed-120
  expression_model: vit-face-expression
age:
  age_model: age_net.caffemodel
  age_proto: age_deploy.prototxt
  root_path: /Volumes/Devo/mldata/age_gender
gender:
  gender_model: gender_net.caffemodel
  gender_proto: gender_deploy.prototxt
  root_path: /Volumes/Devo/mldata/age_gender
variation:
  model: sd-image-variations-diffusers
upscale:
  root: upscalers
lora:
  root: LORA
  root_xl: LORAXL
  root_3: LORA3
  root_flux: FLUX
  root_qwen: QWEN
textual_inversion:
  root: TI
  root_2: TI2
  root_xl: TIXL
  root_3: TI3
face2img:
  default_model: juglight
  face_store: /Volumes/Devo/mldata/faces
img2caption:
  model: blip-large-long-cap
deepface:
  age: age_model_weights.h5
  race: race_model_single_batch.h5
image2text:
  model: sk_invoice_receipts
  tokenizer: sk_invoice_receipts
streetview:
  local_url: http://192.168.0.10:21234/
  url: https://geo.cacko.net/